# Generated by Django 5.2 on 2025-04-29 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
