# Generated by Django 5.2 on 2025-04-29 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_module', '0003_topic_grade_topic'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIUsageStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_count', models.IntegerField(default=0)),
                ('success_count', models.IntegerField(default=0)),
                ('total_response_time', models.FloatField(default=0.0)),
                ('last_24h_requests', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Статистика использования AI',
                'verbose_name_plural': 'Статистика использования AI',
            },
        ),
    ]
