# Generated by Django 5.2.1 on 2025-05-13 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_module', '0005_group_aigroupreport_studentcourse_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aiusagestats',
            options={},
        ),
        migrations.AddField(
            model_name='aigroupreport',
            name='is_latest',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aireport',
            name='is_latest',
            field=models.BooleanField(default=False),
        ),
    ]
